Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Function: 
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BIRTHDAYBOT
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Name: DAILY
            Schedule: cron(00 15 ? * * *)